[package]
name = "speedreader-ffi"
version = "0.1.0"
authors = ["Huy Nguyen <huynq.cntt@gmail.com>"]
edition = "2018"

[dependencies]
speedreader = { path = "../lib/" }
libc = "0.2.7"
[patch.crates-io]
cssparser = { git = 'https://github.com/AndriusA/rust-cssparser', branch = "glibc" }

[profile.release]
panic = "abort"

[lib]
name = "speedreader_ffi"
path = "lib.rs"
crate-type = ["staticlib", "cdylib", "rlib"]
